services:
  app-dev:
    build:
      context: .
      dockerfile: dockerFile
      target: base
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - BETTER_AUTH_SECRET=SYGYWkrlLVbiZfLB2xmwQ7DIsVgb9ugk
      - BETTER_AUTH_URL=http://localhost:3000
      - DATABASE_URL=postgresql://mohidnaeem41:HTND7swVJo6b@ep-withered-voice-a1cfkz48-pooler.ap-southeast-1.aws.neon.tech/nigheban?sslmode=require
      - EDGE_STORE_ACCESS_KEY=GG4TUTob6jva0Dkv3mzsai8FK3zk2MJi
      - EDGE_STORE_SECRET_KEY=L81NP9PAWyIKXY2Gup2kY4GMykWln7TRyd6LyeMvpH1P2xdO
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev
    restart: unless-stopped

  app-prod:
    build:
      context: .
      dockerfile: dockerFile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - BETTER_AUTH_SECRET=SYGYWkrlLVbiZfLB2xmwQ7DIsVgb9ugk
      - BETTER_AUTH_URL=http://localhost:3000
      - DATABASE_URL=postgresql://mohidnaeem41:HTND7swVJo6b@ep-withered-voice-a1cfkz48-pooler.ap-southeast-1.aws.neon.tech/nigheban?sslmode=require
      - EDGE_STORE_ACCESS_KEY=GG4TUTob6jva0Dkv3mzsai8FK3zk2MJi
      - EDGE_STORE_SECRET_KEY=L81NP9PAWyIKXY2Gup2kY4GMykWln7TRyd6LyeMvpH1P2xdO
    command: pnpm start
    restart: unless-stopped
